services:
  nginx:
    image: nginx:alpine
    container_name: dockcampus-nginx
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - backend
      - frontend

  db:
    image: postgres:16
    container_name: dockcampus-db
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "0.0.0.0:5432:5432"

  container-engine:
    build: ./container-engine
    container_name: dockcampus-container-engine
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL_RUST}
      RUST_LOG: ${RUST_LOG}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8001:8001"
    depends_on:
      - db

  backend:
    build: ./backend
    container_name: dockcampus-backend
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - container-engine

  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    container_name: dockcampus-frontend
    restart: unless-stopped
    env_file:
      - .env
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
